site: Carol Gunby

url: https://carolgunby.com
baseurl: 

collections:
  pages:
    output: false
    permalink: /:name
  samples:
    output: true
    permalink: /samples/:slug:output_ext

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "samples"
    values:
      layout: "sample"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

google_analytics: G-FPG0952SCP