basic_settings:
  site_title: Carol Gunby
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/new-headshot.jpg 
  logo_width: 110

menu_settings:
  menu_items:
    - title: 'Samples'
      url: '/samples/'

footer_settings:
  footer_tagline: 

hero_settings:
  overlay_opacity: 0.8

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  linkedin_url: 'https://linkedin.com/in/carolgunby'
  github_url: 'https://github.com/rakuista'

color_settings:
  background_color: '#e7e8e9'
  background_alt_color: '#247BA0'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#3498db'
  border_color: '#dddddd'
  hero_background_color: '#132930'
  hero_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;600&family=Source+Serif+Pro:ital@0;1&display=swap" rel="stylesheet">'
  title_font: '"Rubik", sans-serif'
  body_font: '"Source Serif Pro", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 600
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 30
    medium_size: 36
    large_size: 42
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 18
    medium_size: 20
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.4
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""